name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install requirements
      run: |
        pip install -U pip setuptools
        pip install -r requirements.txt
    - name: Run validation test
      run: python3 -m pytest validate_csv.py
