name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-slim

    steps:
    - uses: actions/checkout@v7
    - name: Set up uv
      uses: astral-sh/setup-uv@v7
    - name: Run validation test
      run: uvx --with-requirements requirements.txt pytest validate_csv.py
